# Generated by Django 6.0.5 on 2026-05-25 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('traceback', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('user_role', models.CharField(default='anonymous', max_length=20)),
                ('post_data', models.TextField(blank=True, default='{}')),
                ('extra', models.TextField(blank=True, default='{}')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Error Log',
                'verbose_name_plural': 'Error Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_title', models.CharField(default="We'll be right back!", max_length=200)),
                ('maintenance_message', models.TextField(default="EduLMS is currently undergoing scheduled maintenance. We'll be back shortly. Thank you for your patience.")),
                ('maintenance_end_time', models.DateTimeField(blank=True, help_text='Expected time maintenance ends (shown to users). Leave blank to hide.', null=True)),
                ('maintenance_started', models.DateTimeField(blank=True, null=True)),
                ('banner_enabled', models.BooleanField(default=False)),
                ('banner_message', models.CharField(blank=True, max_length=300)),
                ('banner_type', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('success', 'Success'), ('danger', 'Danger')], default='info', max_length=10)),
                ('banner_link', models.URLField(blank=True)),
                ('banner_dismissible', models.BooleanField(default=True)),
                ('allow_student_registration', models.BooleanField(default=True)),
                ('allow_teacher_registration', models.BooleanField(default=True)),
                ('registration_message', models.CharField(blank=True, help_text='Shown when registration is closed.', max_length=300)),
                ('school_name', models.CharField(blank=True, max_length=200)),
                ('school_contact_email', models.EmailField(blank=True, max_length=254)),
                ('school_contact_phone', models.CharField(blank=True, max_length=30)),
                ('school_website', models.URLField(blank=True)),
                ('school_address', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
