# Generated by Django 4.2.30 on 2026-05-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_title', models.CharField(default='System Maintenance', max_length=255)),
                ('maintenance_message', models.TextField(default='We are currently upgrading EduLMS to improve your experience. Please check back shortly.')),
                ('maintenance_end_time', models.DateTimeField(blank=True, null=True)),
                ('school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('school_contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Maintenance Setting',
                'verbose_name_plural': 'Maintenance Settings',
            },
        ),
    ]
